name: iec

on:
  push:
    branches: [ master ]
#    tags:
#      - 0.*
  pull_request:
    branches: [ master ]
#    tags:
#      - 0.*

jobs:
  build-and-publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
#    - name: Add msbuild to PATH
#      uses: microsoft/setup-msbuild@v1.0.2        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack package
      if: startsWith(github.ref, 'refs/tags/0.')
      run: dotnet pack IEC.Target.SqlServer\IEC.Target.SqlServer.csproj -p:TargetFrameworks=net5 -c:Release
    - name: xcopy
      if: startsWith(github.ref, 'refs/tags/0.')
      run: xcopy /Y IEC.Target.SqlServer\bin\Release\*.nupkg .
    - name: Publish package
      if: startsWith(github.ref, 'refs/tags/0.')
      run: dotnet nuget push IEC*.nupkg --api-key ${{secrets.NUGET_PUBLISH_SECRET}} --source https://api.nuget.org/v3/index.json